### ISSUE TITLE
wow.realmStatus "realms" parameter is not optional

### ISSUE THREAD

**Issue by amyspark** [benweier/battlenet-api#17]
If I try to use the wow.realmStatus API without providing at least an empty array, a TypeError is generated.

Version: 0.10.1

```
D:\Documents\Amyspark\TheSilvermoonSentinelBook\node_modules\battlenet-api\lib\w
ow\realm.js:12
      realms: args.params.realms.toString()
                                ^
TypeError: Cannot read property 'toString' of undefined
    at Object.realmStatus (D:\Documents\Amyspark\TheSilvermoonSentinelBook\node_
modules\battlenet-api\lib\wow\realm.js:12:33)
    at D:\Documents\Amyspark\TheSilvermoonSentinelBook\main.js:27:14
    at _setImmediate (D:\Documents\Amyspark\TheSilvermoonSentinelBook\node_modul
es\async\lib\async.js:187:20)
    at iterate (D:\Documents\Amyspark\TheSilvermoonSentinelBook\node_modules\asy
nc\lib\async.js:265:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (D:\Documents\Amyspark\Th
eSilvermoonSentinelBook\node_modules\async\lib\async.js:284:9)
    at Object.async.forEachSeries.async.eachSeries (D:\Documents\Amyspark\TheSil
vermoonSentinelBook\node_modules\async\lib\async.js:220:22)
    at Object.<anonymous> (D:\Documents\Amyspark\TheSilvermoonSentinelBook\main.
js:24:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by benweier** [comment]
Thanks @amyspark 0.10.2 is now out with this fix
